
Media release February 13, 2019

* 世界の有機地域は史上最高に達している
** 7000万ヘクタールの近くの農地は有機になっている
** 世界中の有機農業に関する最新の世界的データは、ドイツのニュルンベルクで開催された世界有数の有機食品見本市であるBIOFACHの有機農業研究所（FiBL）およびIFOAM  -  Organics Internationalによって発表されます。 統計年鑑「世界の有機農業」は、2019年2月13日水曜日の午後4時から午後4時45分まで、NCC EastのHall Shanghaiで開催されます。
** 世界の有機市場は世界的に成長を続けており、970億ドルに達しています

The market research company Ecovia Intelligence estimates that the global market for organic food reached 97 billion US dollars in 2017 (approx. 90 billion euros). 

The United States is the leading market with 40 billion euros, followed by Germany (10 billion euros), France (7.9 billion euros), and China (7.6 billion euros). 

In 2017, many major markets continued to show double-digit growth rates, and the French organic market grew by 18 percent. The Swiss spent the most on organic food (288 Euros per capita in 2017). Denmark had the highest organic market share (13.3 percent of the total food market).

** Almost three million producers worldwide

In 2017, 2.9 million organic producers were reported, which is 5 percent more than in
2016. India continues to be the country with the highest number of producers (835’200),
followed by Uganda (210’352), and Mexico (210’000). 


** Record growth of the organic farmland: 20 percent increase

A total of 69.8 million hectares were organically managed at the end of 2017,
representing a growth of 20 percent or 11.7 million hectares over 2016, the largest
growth ever recorded. Australia has the largest organic agricultural area (35.6 million
hectares), followed by Argentina (3.4 million hectares), and China (3 million hectares).
Due to the large area increase in Australia, half of the global organic agricultural land
is now in Oceania (35.9 million hectares). Europe has the second largest area (21
percent; 14.6 million hectares), followed by Latin America (11.5 percent; 8 million
hectares). The organic area increased in all continents. 

** Ten percent or more of the farmland is organic in fourteen countries

Globally, 1.4 percent of the farmland is organic. However, many countries have far
higher shares. The countries with the largest organic share of their total farmland are
Liechtenstein (37.9 percent), Samoa (37.6 percent), and Austria (24 percent). In fourteen
countries, 10 percent or more of all agricultural land is organic.

** Global organic statistics show the contribution of organic agriculture to the Sustainable Development Goals
According to Dr. Monica Rubiolo from SECO and Joseph Wozniak from ITC “global
data on organic production and markets are of high relevance for policy makers and
contribute to understanding the importance of organic farming in the different
countries.”

“This publication shows our ongoing engagement with transparency in the organic
sector” say Professor Urs Niggli, FiBL director, and Louise Luttikholt, IFOAM –
Organics International Executive Director. And they add “This publication also
demonstrates the contribution of organic agriculture to the Sustainable Development
Goals. Overall, the yearbook shows the potential organic farming has to contribute to a
sustainable future!”

* より詳しい情報
** 書籍を注文するか、ダウンロードする

The printed version of “The World of Organic Agriculture” (30 Euros + postage;
affiliates of IFOAM – Organics International: 20 Euros) can be ordered and
downloaded at https://shop.fibl.org/ (order number 2020) and https://shop.ifoam.bio/.
“The World of Organic Agriculture” as well as graphs and infographics can be
downloaded at www.organic-world.net/yearbook/yearbook-2019.html

** Online database

Tables with more details on crops, markets, and international trade, as well as
explanations can be found on FiBL’s new statistics website https://statistics.fibl.org.
Contacts

• Dr. Helga Willer, FiBL, Ackerstrasse 113, 5070 Frick, Switzerland
Phone +41 (0)79 218 06 26, helga.willer@fibl.org, www.fibl.org
• Louise Luttikholt, IFOAM – Organics International, Charles-de-Gaulle-Strasse
5, 53113 Bonn, Germany
Phone +49 (0)160 8041557, Fax +49 (0)228 9265099, l.luttikholt@ifoam.bio,
www.ifoam.bio
Programme of the session “The World of Organic Agriculture – Statistics and
Emerging Trends”
Wednesday, February 13, 2019, 4:00 to 4:45 pm, Hall Shanghai (NCC East),
NürnbergMesse, Nürnberg
• Louise Luttikholt, IFOAM – Organics International, Moderator
• Dr. Monica Rubiolo, Swiss State Secretariat for Economic Affairs (SECO),
Switzerland
• Dr. Helga Willer, FiBL: The adventure of 20 years of data collection on organic
agriculture
• Julia Lernoud, FiBL: Latest data on organic agriculture worldwide
• Beate Huber, FiBL: Standards and regulations
• Amarjit Sahota, Ecovia Intelligence, UK: The global market for organic food
より詳しい情報は以下にあります。
www.biofach.fibl.org/en/biofach-2019.html

サポート機関
• Swiss State Secretariat for Economic Affairs (SECO)
• International Trade Centre (ITC)
• Coop Sustainability Fund, Coop Switzerland
• NürnbergMesse, the organizers of the BIOFACH fair

The views expressed in this press release can in no way be taken to reflect the official
opinions of SECO, ITC, or NürnbergMesse.
Reference
Helga Willer and Julia Lernoud (Eds.) (2019): The World of Organic Agriculture.
Statistics and Emerging Trends 2019. Research Institute of Organic Agriculture (FiBL),
Frick and IFOAM – Organics International, Bonn. Available at www.organicworld.net/yearbook/yearbook-2019.html

** このメディアリリースはオンラインで提供されます
このメディアリリースとグラフは次のオンラインでアクセス可能です。
www.fibl.org/en/media.html.

* FiBLについて

The Research Institute of Organic Agriculture FiBL is one of the world’s leading institutes
in the field of organic agriculture. FiBL’s strengths lie in its interdisciplinary research,
innovations developed jointly with farmers and the food industry, and rapid knowledge
transfer. FiBL employs some 300 staff at its various locations.
Homepage: www.fibl.org

* Yearbook "The World of Organic Agriculture"

** About "The World of Organic Agriculture"

The yearbook (352 pages) presents the results of the annual survey
on organic agriculture worldwide and has numerous tables, graphs,
maps, and infographics. Furthermore, it contains reports authored
by experts on the organic sector and emerging trends in all regions
and selected countries. In addition, background information on
standards and legislation, policy support, and the global market for
organic food is provided. The book also contains an article about
organic cotton and a chapter reviewing key commodities certified by
selected Voluntary Sustainability Standards (VSS). Further
information and download is available at www.organicworld.net/yearbook/yearbook-2019.html.

** Data collection

The data on organic agriculture is collected annually by the Research Institute of
Organic Agriculture FiBL in collaboration with many partners from around the world.
The results are published jointly with IFOAM – Organics International. The activities
are supported by the Swiss State Secretariat for Economic Affairs (SECO), the
International Trade Centre (ITC), the Coop Sustainability Fund, and NürnbergMesse,
the organizers of the BIOFACH fair.

** 引用

- Helga Willer and Julia Lernoud (Eds.) (2019): The World of Organic Agriculture.
- Statistics and Emerging Trends 2019. Research Institute of Organic Agriculture

** 注文とダウンロード
印刷版は 30ユーロ+ 送料で IFOAM - Organics Internationalの会員は20ユーロで
 https://shop.fibl.org/chen (order number 1076) もしくは https://shop.ifoam.bio/ から注文できます。 
そして www.organic-world.net/yearbook/yearbook-2019.html フリーダウンロードにて書籍は入手できます。

** オンラインデータベース

ここにオンラインのデータベースがあります。
https://statistics.fibl.org.

ホール1のBIOFACH in Hall 1, Stands 1-553（FiBL）1-451 (IFOAM Organics International)にてコピーを手に入れてください。






